In [2]:
import numpy as np

In [5]:
arr=np.arange(0,10)
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
arr_copy=arr.copy()
arr_copy[:]=100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [3]:
arr_2d=np.array(
    [
        [3,6,9],
        [12,15,18],
        [21,24,27]

    ]
)
arr_2d

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

In [20]:
arr_2d>25

array([[False, False, False],
       [False, False, False],
       [False, False,  True]])

In [21]:
import numpy as np
dice_rolls = np.array([3, 1, 5, 2, 5, 1, 1, 5, 1, 4, 2, 1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6, 3, 6, 2, 3, 5, 6, 5])

total_rolls_over_two = dice_rolls>2
len(total_rolls_over_two)

29